language: objective-c
osx_image: xcode8.1
rvm:
- 2.2
before_install:
- chmod a+x ./TravisScripts/install.sh
- chmod a+x ./TravisScripts/build.sh
install:
- ./TravisScripts/install.sh
script:
- ./TravisScripts/build.sh
general:
  branches:
    only:
      - staging